services:
  postgres:
    image: 'postgres:latest'
    container_name: 'highload_users_db'
    environment:
      - 'POSTGRES_DB=users'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
