services:
  postgres-social-network-1:
    container_name: postgres-social-network-1
    image: "postgres:latest"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5442:5432"
    command: ["postgres", "-c", "log_statement=all"]

  redis:
    image: 'redis:latest'
    ports:
      - '6379'

  rabbitmq:
    image: "rabbitmq:4.1-rc-management"
    ports:
      - "15672:15672"
      - "5672:5672"