services:
  postgres-social-network-1:
    container_name: postgres-social-network-1
    image: "postgres:latest"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5442:5432"