logging:
  level:
    org.springframework.security: trace

spring:
  application:
    name: highload

  security:
    user:
      name: user
      password: password
    oauth2:
      authorizationserver:
        client:
          public-client:
            registration:
              client-id: "public-client"
              client-authentication-methods:
                - "none"
              authorization-grant-types:
                - "authorization_code"
              redirect-uris:
                - "http://127.0.0.1:3000"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true
            require-proof-key: true