server:
  port: 8080

spring:
  application:
    name: gateway
  devtools:
    livereload:
      enabled: true
      port: 35279
  docker:
    compose:
      enabled: false
  cloud:
    gateway:
      mvc:
        routes:
          - id: users
            uri: http://localhost:8081/
            predicates:
              - Path=/users

